export const UI_STATE_KEYS = {
  scenarioTitle: "ui.scenarioTitle",
  stageTitle: "ui.stageTitle",
  flowPanelVisible: "ui.flowPanelVisible",
  flowPanelTitle: "ui.flowPanelTitle",
  flowPanelMessage: "ui.flowPanelMessage",
  flowPanelPrimaryLabel: "ui.flowPanelPrimaryLabel",
  flowPanelSecondaryLabel: "ui.flowPanelSecondaryLabel",
  flowPanelTertiaryLabel: "ui.flowPanelTertiaryLabel",
  dialogueVisible: "ui.dialogueVisible",
  dialogueTitle: "ui.dialogueTitle",
  dialogueSpeaker: "ui.dialogueSpeaker",
  dialogueMessage: "ui.dialogueMessage",
  dialogueHint: "ui.dialogueHint",
  dialogueBackgroundPath: "ui.dialogueBackgroundPath",
  dialogueStandingPath: "ui.dialogueStandingPath",
  dialogueLogVisible: "ui.dialogueLogVisible",
  dialogueLogText: "ui.dialogueLogText",
  dialogueLogButtonLabel: "ui.dialogueLogButtonLabel",
  dialogueAutoPlayActive: "ui.dialogueAutoPlayActive",
  dialogueAutoPlayButtonLabel: "ui.dialogueAutoPlayButtonLabel",
  headerHint: "ui.headerHint",
  headerTimer: "ui.headerTimer",
  statusMessage: "ui.statusMessage",
  battleSummary: "ui.battleSummary",
  selectedUnitId: "ui.selectedUnitId",
  unitDetailVisible: "ui.unitDetailVisible",
  unitDetailTitle: "ui.unitDetailTitle",
  unitDetailBody: "ui.unitDetailBody",
  unitDetailHint: "ui.unitDetailHint"
} as const;

export const DEFAULT_UI_STATE = {
  [UI_STATE_KEYS.scenarioTitle]: "Scenario: -",
  [UI_STATE_KEYS.stageTitle]: "Stage: -",
  [UI_STATE_KEYS.flowPanelVisible]: false,
  [UI_STATE_KEYS.flowPanelTitle]: "",
  [UI_STATE_KEYS.flowPanelMessage]: "",
  [UI_STATE_KEYS.flowPanelPrimaryLabel]: "",
  [UI_STATE_KEYS.flowPanelSecondaryLabel]: "",
  [UI_STATE_KEYS.flowPanelTertiaryLabel]: "",
  [UI_STATE_KEYS.dialogueVisible]: false,
  [UI_STATE_KEYS.dialogueTitle]: "",
  [UI_STATE_KEYS.dialogueSpeaker]: "",
  [UI_STATE_KEYS.dialogueMessage]: "",
  [UI_STATE_KEYS.dialogueHint]: "SPACE or click to continue",
  [UI_STATE_KEYS.dialogueBackgroundPath]: "",
  [UI_STATE_KEYS.dialogueStandingPath]: "",
  [UI_STATE_KEYS.dialogueLogVisible]: false,
  [UI_STATE_KEYS.dialogueLogText]: "",
  [UI_STATE_KEYS.dialogueLogButtonLabel]: "Show Log",
  [UI_STATE_KEYS.dialogueAutoPlayActive]: false,
  [UI_STATE_KEYS.dialogueAutoPlayButtonLabel]: "Auto Off",
  [UI_STATE_KEYS.headerHint]: "Header: drag timer idle",
  [UI_STATE_KEYS.headerTimer]: "5.00s",
  [UI_STATE_KEYS.statusMessage]: "Ready: drag an ally. Battle resolves on release or after 5 seconds.",
  [UI_STATE_KEYS.battleSummary]: "Battles: 0. Defeated: none",
  [UI_STATE_KEYS.selectedUnitId]: "-",
  [UI_STATE_KEYS.unitDetailVisible]: false,
  [UI_STATE_KEYS.unitDetailTitle]: "",
  [UI_STATE_KEYS.unitDetailBody]: "",
  [UI_STATE_KEYS.unitDetailHint]: "Click to close"
} as const;
