export const UI_STATE_KEYS = {
  scenarioTitle: "ui.scenarioTitle",
  stageTitle: "ui.stageTitle",
  flowPanelVisible: "ui.flowPanelVisible",
  flowPanelTitle: "ui.flowPanelTitle",
  flowPanelMessage: "ui.flowPanelMessage",
  flowPanelPrimaryLabel: "ui.flowPanelPrimaryLabel",
  flowPanelSecondaryLabel: "ui.flowPanelSecondaryLabel",
  flowPanelTertiaryLabel: "ui.flowPanelTertiaryLabel",
  dialogueVisible: "ui.dialogueVisible",
  dialogueTitle: "ui.dialogueTitle",
  dialogueSpeaker: "ui.dialogueSpeaker",
  dialogueMessage: "ui.dialogueMessage",
  dialogueHint: "ui.dialogueHint",
  dialogueBackgroundPath: "ui.dialogueBackgroundPath",
  dialogueStandingPath: "ui.dialogueStandingPath",
  headerHint: "ui.headerHint",
  headerTimer: "ui.headerTimer",
  statusMessage: "ui.statusMessage",
  battleSummary: "ui.battleSummary",
  selectedUnitId: "ui.selectedUnitId"
} as const;

export const DEFAULT_UI_STATE = {
  [UI_STATE_KEYS.scenarioTitle]: "Scenario: -",
  [UI_STATE_KEYS.stageTitle]: "Stage: -",
  [UI_STATE_KEYS.flowPanelVisible]: false,
  [UI_STATE_KEYS.flowPanelTitle]: "",
  [UI_STATE_KEYS.flowPanelMessage]: "",
  [UI_STATE_KEYS.flowPanelPrimaryLabel]: "",
  [UI_STATE_KEYS.flowPanelSecondaryLabel]: "",
  [UI_STATE_KEYS.flowPanelTertiaryLabel]: "",
  [UI_STATE_KEYS.dialogueVisible]: false,
  [UI_STATE_KEYS.dialogueTitle]: "",
  [UI_STATE_KEYS.dialogueSpeaker]: "",
  [UI_STATE_KEYS.dialogueMessage]: "",
  [UI_STATE_KEYS.dialogueHint]: "SPACE or click to continue",
  [UI_STATE_KEYS.dialogueBackgroundPath]: "",
  [UI_STATE_KEYS.dialogueStandingPath]: "",
  [UI_STATE_KEYS.headerHint]: "Header: drag timer idle",
  [UI_STATE_KEYS.headerTimer]: "5.00s",
  [UI_STATE_KEYS.statusMessage]: "Ready: drag an ally. Battle resolves on release or after 5 seconds.",
  [UI_STATE_KEYS.battleSummary]: "Battles: 0. Defeated: none",
  [UI_STATE_KEYS.selectedUnitId]: "-"
} as const;
